alias(
    name = "x86_64-linux-autosd10-platform",
    actual = "@score_bazel_platforms//:x86_64-linux-autosd10",
    visibility = ["//visibility:public"],
)

alias(
    name = "x86_64-linux-autosd10-toolchain",
    actual = "@score_autosd10_x86_64_toolchain//:x86_64-linux-autosd10",
    visibility = ["//visibility:public"],
)
